name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
      
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run Biome check
        run: pnpm biome:check
        id: biome
        continue-on-error: true
      
      - name: Run tests
        run: pnpm test
        id: test
        continue-on-error: true
      
      - name: Check results
        run: |
          if [ "${{ steps.biome.outcome }}" == "failure" ]; then
            echo "❌ Biome check failed"
            exit 1
          else
            echo "✅ Biome check passed"
          fi
          
          if [ "${{ steps.test.outcome }}" == "failure" ]; then
            echo "❌ Tests failed"
            exit 1
          else
            echo "✅ Tests passed"
          fi
        shell: bash